site_name: Free Cloud Services
theme: readthedocs
docs_dir: 'doc'
nav:
    - 'Home': 'index.md'
    - 'Datastores':
        - 'MongoDB Atlas': 'datastores/mongo.md'
        - 'Redis': 'datastores/redis.md'
        - 'Backblaze S3': 'datastores/backblaze.md'